### ISSUE TITLE
An observation from PlotAI-GDP-demo.mp4

### ISSUE THREAD

**Issue by CatChenal** [mljar/plotai#1]
The initial prompt was: "scatter plot gdp vs happiness", meaning you requested a graph of **y=gdp vs x=happiness**, but the `make` function yielded a graph of **y=happiness vs x=gdp** with the wrong title.
I would call that a bug.

**Comment by pplonski** [comment]
Looks like an issue with ChatGPT, there is an option to add in prompt sentence to make sure that axis labels are ok.
