### ISSUE TITLE
Ability to disable Logger

### ISSUE THREAD

**Issue by feynmanliang** [mljar/plotai#10]
We are using PlotAI inside of Mercury and would like to only output plots without the prompt/response. Can we make it easy to disable the logger? e.g. `plot(prompt, verbose=False)`?

**Comment by pplonski** [comment]
Hi @feynmanliang,

we can try :) @Marchlak could you please take a look on it?

@feynmanliang what is your use case for PlotAi and Mercury?

**Comment by feynmanliang** [comment]
Amazing, love it and I am happy to contribute a PR if you need.

We are making some quick demos around how a DIY on-prem version of julius.ai would look.

**Comment by pplonski** [comment]
Is it done! @Marchlak has added `verbose` parameter in `PlotAI()` constructor (#12). Happy plotting :)

**Comment by feynmanliang** [comment]
Amazing, thank you!!
