### ISSUE TITLE
GPT 4 official support

### ISSUE THREAD

**Issue by augustocrmg** [mljar/plotai#2]
Hello, i am trying to use plotai with a GPT4 key, but after several ways i have not been succesful using chat2plot with GPT4. Does caht2plot have official support to GPT 4 ? You guys can provide a implementation example with GPT4 if it's possible ?

**Comment by pplonski** [comment]
Hi @augustocrmg,

You need to change the model in this line https://github.com/mljar/plotai/blob/9d5afe5c01c405fedb57271b1836c9915ae5892a/plotai/llm/openai.py#L15

to setup GPT4. I prefered GPT 3.5 because it is faster and cheaper.

**Comment by augustocrmg** [comment]
When i try to use this code from your examples: 

`
df = pd.DataFrame({"x":[1,2,3], "y": [4,5,6]})
plot = PlotAI(df,model=llm.engine)
`

i obtain this error, note that i tested the key with another call and its valid: 

`
InvalidRequestError                       Traceback (most recent call last)
File /anaconda/envs/gpt_develop/lib/python3.10/site-packages/plotai/plotai.py:43, in PlotAI.make(self, prompt)
     39 p = Prompt(prompt, self.df, self.x, self.y, self.z)    
     41 Logger().log({"title": "Prompt", "details": p.value})
---> 43 response = ChatGPT().chat(p.value)
     45 Logger().log({"title": "Response", "details": response})
     47 executor = Executor()

File /anaconda/envs/gpt_develop/lib/python3.10/site-packages/plotai/llm/openai.py:48, in ChatGPT.chat(self, prompt)
     37 def chat(self, prompt):
     39     params = {
     40         **self._default_params,
     41         "messages": [
   (...)
     46         ],
     47     }
---> 48     response = openai.ChatCompletion.create(**params)
     49     return response["choices"][0]["message"]["content"]

File /anaconda/envs/gpt_develop/lib/python3.10/site-packages/openai/api_resources/chat_completion.py:25, in ChatCompletion.create(cls, *args, **kwargs)
     23 while True:
     24     try:
---> 25         return super().create(*args, **kwargs)
     26     except TryAgain as e:
     27         if timeout is not None and time.time() > start + timeout:

File /anaconda/envs/gpt_develop/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py:149, in EngineAPIResource.create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    127 @classmethod
    128 def create(
    129     cls,
   (...)
    136     **params,
    137 ):
    138     (
    139         deployment_id,
    140         engine,
    141         timeout,
    142         stream,
    143         headers,
    144         request_timeout,
    145         typed_api_type,
    146         requestor,
    147         url,
    148         params,
--> 149     ) = cls.__prepare_create_request(
    150         api_key, api_base, api_type, api_version, organization, **params
    151     )
    153     response, _, api_key = requestor.request(
    154         "post",
    155         url,
   (...)
    160         request_timeout=request_timeout,
    161     )
    163     if stream:
    164         # must be an iterator

File /anaconda/envs/gpt_develop/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py:83, in EngineAPIResource.__prepare_create_request(cls, api_key, api_base, api_type, api_version, organization, **params)
     81 if typed_api_type in (util.ApiType.AZURE, util.ApiType.AZURE_AD):
     82     if deployment_id is None and engine is None:
---> 83         raise error.InvalidRequestError(
     84             "Must provide an 'engine' or 'deployment_id' parameter to create a %s"
     85             % cls,
     86             "engine",
     87         )
     88 else:
     89     if model is None and engine is None:

InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>
`

**Comment by augustocrmg** [comment]
I belive that with the update to GPT4 it is necessary to use these parameters, is there any way for me to use them with plotai ?

**Comment by pplonski** [comment]
Hi @augustocrmg,

we need to change PlotAI contructor to accept `model` argument. Would you like to provide PR?

**Comment by augustocrmg** [comment]
Yes i can do it, and i had some other ploblems with the deployment id that needs to be passed when development is being carrid out on azure plataforms, i will add this in the pull request too

**Comment by pedMatias** [comment]
Hi there
@pplonski I opened a PR to fix this, and also fix some dependencies. Let me know if there is anything you want to me to fix.
Cheers

PS: Great work @pplonski, the project is quite cool

**Comment by pplonski** [comment]
Added in #3 - thank you @pedMatias
